Nutlope/aicommits

aicommits.ts

Windows is not happy with single quote inside `execSync` 
Fixing #7

Update execSync command to use backticks instead of single quotes.

---

aicommits.ts

Such an awesome tool, thanks for this 🙌
This PR adds the lockfile from `pnpm` to the git diff exclusion list.

excluding pnpm-lock.yaml from git diff

---

README.md
aicommits.ts
package.json

This pull request updates the name of the environment variable for the OpenAI API key in the README file and source code. The new name is `OPENAI_KEY` and the previous name, `OPENAI_API_KEY`, is used as a fallback.
Addressing #1

Rename environment variable for OpenAI API key

---

package.json
pnpm-lock.yaml
src/cli.ts

We were manually constructing the request with `node-fetch` which was frail, had no error-handling, or types.
Use the `openai` package for better error-handling and types.

refactor: use `openai` package

---

.github/workflows/test.yml

When contributors open PRs, there are no basic checks that help with streamlining review.
Add GitHub Actions to automatically check if the code builds and passes the linter.

ci: add github actions for linting & type-checking

---

README.md
package.json
pnpm-lock.yaml
src/cli.ts
src/utils.ts

Exporting private tokens to the shell environment is insecure because it can be accessed by any command from any directory.
Other tools like  npm doesn't accept the token as an environment variable: https://github.com/npm/npm/issues/8356
- Follow npm's approach of having a config file in the home directory in [ini format](https://www.npmjs.com/package/ini) that can store the token, amongst other things in the future.
- Updated docs to include new instructions

feat: config file at `~/.aicommits`

---

package.json
pnpm-lock.yaml
src/cli.ts
tsconfig.json

- Code wasn't compiled in TypeScript Strict mode
- Enabling strict mode required getting types for `inquirer`. But upon installing `@types/inquirer`, it complained that it's a module and can't be imported unless it's from a module
- The tsconfig target was set to `es2016`, which is [below Node 8](https://github.com/microsoft/TypeScript/wiki/Node-Target-Mapping) and very outdated
- Enable Strict mode
- Use `module` type package and update to Node 16 resolution 
- Up the target to `ES2020`, which is Node 14 (currently in LTS but [approaching end of life in April](https://github.com/nodejs/release#release-schedule))

build: strict mode, use esm, and target es2020

---

package.json
pnpm-lock.yaml
src/cli.ts

- The code is currently using `execSync` but it's not recommended to use because it doesn't properly handle passing in separate arguments (everything is passed in as a single string). We can use `spawnSync` instead, but it's also synchronous and blocking (and supposedly slower?). Ideally there's a promise based API.
- Use `execa` which offers a Promise based API around `spawn`. It also adds cross platform compatibility, always returns utf8 encoded output, and throws on erroneous exit codes.

refactor: use execa

---

.github/CONTRIBUTING.md
.github/workflows/test.yml
package.json
pnpm-lock.yaml
src/cli.ts
tsconfig.json

- Using TypeScript compiler is slow and lacking in DX features
- No watch mode for iterating
- No bundles for a smaller output
- Use pkgroll (Basically a no-config wrapper around [Rollup](https://npmjs.com/package/rollup) & esbuild) to build. It's a lot faster and has watch mode.
- We'll see more benefits later on when we prepare for faster npm installation by bundling dependencies and minifying distribution.
- Added a [Contributing guide](https://github.com/privatenumber/aicommits/blob/pkgroll/.github/CONTRIBUTING.md) that explains the commands for development
```
$ hyperfine 'pnpm pkgroll' 'pnpm tsc'
Benchmark 1: pnpm pkgroll
Time (mean ± σ):     775.4 ms ±  14.0 ms    [User: 643.2 ms, System: 114.0 ms]
Range (min … max):   757.0 ms … 806.6 ms    10 runs
Benchmark 2: pnpm tsc
Time (mean …
```

build: use pkgroll

---

src/utils.ts

The prompt message takes up precious character count, so it should always be as short as possible.
I played around with https://chat.openai.com and this prompt seems to work pretty well.
I think the "I want you to act like a ..." prompt works well when there's a dialogue, but in this case, I think being direct is better.

refactor: gpt-3 prompt to be more concise

---

src/utils.ts

* https://github.com/nodejs/nodejs.dev/issues/150
* https://www.theserverside.com/video/Follow-these-git-commit-message-guidelines#:~:text=Neither%20a%20git%20subject%20line,well%2Dformed%20grammar%20and%20typesetting.
* Manually remove period from end of response
* Prompting removal seemingly not working

feat: remove ending period

---

package.json
pnpm-lock.yaml

- It was easy to miss minor linting errors and have the CI fail
- Added lint-staged & simple-git-hooks to automatically lint the changes on commit

chore: add commit hooks

---

package.json
pnpm-lock.yaml
src/cli.ts
src/utils.ts

- Add a CLI interface, which supports `--help` and `--version` flags (e.g. `aicommmits --help` shows a manual on how to use the CLI tool)
- Adds a `generate` flag that accepts a number of messages to generate. (`alicommits --generate 3` for 3 messages) Aliased with `g` (e.g. `alicommits -g 3`).
@Nutlope I had go pick a flag name that didn't collide with any [`git commit` flags](https://git-scm.com/docs/git-commit). Feel free to rename if you can think of a better one that doesn't overlap with git commit. 
Using `cleye` will set us up for transparently wrapping `git commit` so we can later pass down any unknown arguments (e.g. signing commits or even adding files `-a`).

feat: show multiple options

---

src/cli.ts

There were requests to support certain `git commit ` features (e.g. https://github.com/Nutlope/aicommits/issues/33).
closes https://github.com/Nutlope/aicommits/issues/33
This passes down unused `argv` down to `git commit` so you can leverage most `git commit` features.
- Support for `git commit -a` will be tricky, because it needs to add the files before aicommits runs

feat: pass down argv to git commit

---

.github/workflows/release.yml
package.json

- `package.json#version` not being bumped: https://github.com/Nutlope/aicommits/pull/88
- Releases can only be made by one person
- Delegate releasing to GitHub Actions by running [`semantic-release`](https://github.com/semantic-release/semantic-release)
This change makes it so that new commits merged to `main` will trigger semantic-release to make a release (if there's a fix/feat commit).
Semantic Release works by looking at the new commits. It parses them based on their format (Angular Commit Message Conventions, which is basically Conventional Commits), and determines what kind of release to make (fix, feature, breaking). And makes a release to GitHub and npm with auto-generated release notes.
- Because releases are automated, there will be less points of failure and more reliable
- …

ci: setup semantic-release

---

src/utils/git.ts

This registers more files to be excluded for these types of projects (specifically, their lock files):
- Python
- Ruby
- Rust

feat: exclude all *.lock files

---

src/utils/openai.ts

closes https://github.com/Nutlope/aicommits/issues/112

feat: link OpenAI status on 500 error

---

src/commands/aicommits.ts
src/utils/openai.ts
tests/specs/cli.ts

the tokenizer that was just added doesnt have support for the new model yet, so still using the told model and 🤞 they are very similar.
I used it to generate its own commit message.

feat: use new gpt-3.5-turbo model

---

src/commands/aicommits.ts
src/commands/prepare-commit-msg-hook.ts

The `spinner.start` function from `clack@promts` package hides terminal cursor, in case of errors the cursor remains hidden. To fix this, I've added a call to `spinner.stop()` before throwing errors. This will unhide the cursor,

fix: restore cursor visibility in case of errors

---

README.md

I ran into a small issue while following the README word by word. The flag to generate some messages needs an argument. This was not clear to me. I hope my change is helpful so that other don't experience the same.

docs: `--generate` value

---

src/utils/git.ts

Exclude files only exclude from display files but 'diff' still take all files

fix: `git diff` to respect excluded files

---

README.md
src/commands/aicommits.ts
src/commands/prepare-commit-msg-hook.ts
src/utils/config.ts
src/utils/openai.ts
tests/specs/cli/commits.ts
tests/specs/config.ts

fixes #184 #91 
closes #120
Setting the default to 50 characters.
> This option is very much needed. So I sped things up for this.  
cc @privatenumber

feat: `max-length` config

---

src/utils/openai.ts
tests/specs/cli/commits.ts

Extracted changes from https://github.com/Nutlope/aicommits/pull/177

refactor: improve commit length enforcement

---

README.md

This update to the README explains the new `type` configuration option, how to set it to "conventional" to generate Conventional Commits, and how to clear this option.
close #213

docs: `type` flag/config for Conventional Commits
