.npmignore
package.json
tsconfig.json

chore: `package.json` refactors

---

aicommits.ts

update prompt wording to specify use of present tense

---

aicommits.ts

Handle OpenAI API errors
Addressing #4 & #5

Fix OpenAI API error handling when generating commit message

---

src/cli.ts
src/index.ts

The extra file that calls `main` was unnecessary overhead

refactor: consolidated src to one file

---

src/cli.ts
src/utils.ts

- Code was written imperatively and was difficult to parse through
- Abstract bits of logic into helper methods so the main code is easier to skim

refactor: create helper methods in utils

---

package.json
pnpm-lock.yaml
src/cli.ts
src/utils.ts

refactor: revamp the UI

---

README.md

Added node version requirements as suggested in #74

docs: add node version requirements to installation

---

src/utils.ts

feat: use imperative present tense in prompt

---

README.md

updated minimum node version. It is important that this information is given to the end user.

docs: specify LTS in minimum Node.js requirement

---

package.json
src/cli.ts
src/commands/aicommits.ts
src/commands/config.ts
src/commands/hook.ts
src/commands/prepare-commit-msg-hook.ts
src/utils/fs.ts

Before, the hook was a separate entry which created complications with pkgroll.
Include the hook in the aicommits entry-point.
Would like to make refactors but they should happen after tests.

refactor: hooks to be called via aicommits

---

src/utils/openai.ts

closes https://github.com/Nutlope/aicommits/issues/97
closes https://github.com/Nutlope/aicommits/pull/98

fix: handle unreachable openai.com

---

src/utils/openai.ts

closes https://github.com/Nutlope/aicommits/issues/90

fix: improve large diff error message

---

README.md

Quick fix for config setup in README

docs: fix config filename in README

---

package.json
pnpm-lock.yaml
src/utils/openai.ts

This replaces #80 
Used `aicommits` to generate the following commit message:
Add dependency '@dqbd/tiktoken' and update OpenAI configuration to use 'text-davinci-003' model

refactor: use tokenizer to accurately count tokens

---

src/utils/openai.ts

fixes https://github.com/Nutlope/aicommits/issues/137

fix: content-length miscalculation bug

---

src/cli.ts
src/commands/aicommits.ts
src/utils/git.ts
tests/specs/cli.ts

I added flag for excluding paths or files.
https://github.com/Nutlope/aicommits/issues/128

feat(cli): `--exclude` flag for ignoring files

---

package.json
pnpm-lock.yaml
src/utils/openai.ts

closes https://github.com/Nutlope/aicommits/issues/161

fix: tokenize with `gpt-3.5-turbo` model

---

README.md
src/cli.ts
src/commands/aicommits.ts
tests/specs/cli/commits.ts
tests/specs/cli/error-cases.ts

feat: `--all` flag

---

src/utils/git.ts

perf: use minimal git diff algorithm

---

src/utils/openai.ts

> Instead of the hard-coded limit error, it will now show the server limit error.
fixes #186 
cc @privatenumber

fix: remove hard-coded token limit

---

README.md
src/commands/aicommits.ts
src/commands/prepare-commit-msg-hook.ts
src/utils/config.ts
src/utils/openai.ts
tests/specs/cli/commits.ts
tests/specs/config.ts

> **10s** is still the default timeout but now it's configurable over the default
fixes #157 
cc @privatenumber

feat: request timeout config
